version: "3"

services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root1234
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysqldb:/var/lib/mysql
      - ./mysql/:/docker-entrypoint-initdb.d/
  parking:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    depends_on:
      - mysql
    stdin_open: true
    restart: always
    tty: true
    ports:
      - 8080:8080
volumes:
  mysqldb: